### ISSUE TITLE
제주공항- 실시간 정보 알려주기

### ISSUE THREAD

**Issue by yujin2019** [King-of-parking-Kimparking/KimparkingMain#5]
제주공항의 경우 실시간 정보로 알려준다.
혼잡도와 현재 주차대수, 주차가능대수, 요금정보

**Comment by RohYounwoo** [comment]
javascript와 실시간 xml 연동 필요

**Comment by RohYounwoo** [comment]
공항 혼잡도 및 실시간 주차장 정보 업데이트 필요

**Comment by RohYounwoo** [comment]
xml 활용 공항 및 실시간 주차장 정보 업데이트 완료
